version: '3.4'

networks:
    docker-net-vpn:
        external: true
services:
  spotsline-backend:
    container_name: ${NEST_CONTAINER_NAME}
    cap_add:
     - NET_ADMIN
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - ${NEST_PORT}:3000
    networks:
      - docker-net-vpn

