version: '3.9'
services:
  frontend:
    build:
      context: ../spotsline-frontend
      dockerfile: Dockerfile
    ports:
      - ${VITE_PORT}:80
    networks:
      - spotsline
    depends_on:
      - backend
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - ${NEST_PORT}:3000
    networks:
      - spotsline
networks:
  spotsline:
